server:
  port: 9094
spring:
  application:
    name: USER-CONSUMER
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7071.com:7071/eureka/,http://eureka-7072.com:7072/eureka/ #告诉服务提供者注册到哪里
feign:
   hystrix:
       enabled: true #开启熔断支持
   client:
       config:
         remote-service:           #服务名，填写default为所有服务
           connectTimeout: 3000
           readTimeout: 3000
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000