server:
  port: 1234
spring:
  application:
    name: ZUUL_GATEWAR
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7071.com:7071/eureka/,http://eureka-7072.com:7072/eureka/ #告诉服务提供者注册到哪里
  instance:
    prefer-ip-address: true
zuul:
  routes:
    myUser.serviceId: user-provider
    myUser.path: /myUser/** #把myUser的访问路径都跳转到user-provider
  ignored-services: "*" #所有服务都不允许以服务名来访问
  prefix: "/services"
  retryable: true
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 3000 # 熔断超时时长：3000ms